# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Chat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chat
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/RemoteConfig'
  

end
